server:
  port: 8090
#  servlet:
#    context-path: /hisystem
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hisman?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: ''
    username: 1208585122@qq.com
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
#  热部署
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      poll-interval: 2000ms
      quiet-period:  1999ms

